services:
  # 1. O Garçom (Leve e rápido)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - banco_dados
    networks:
      - rede_contradito

  # 2. O Cozinheiro (Worker de IA - Isolado)
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    expose:
      - "8001" # RNF08: Expõe a porta ESTRITAMENTE para a rede interna do Docker. Não acessível de fora.
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - banco_dados
    networks:
      - rede_contradito

  # 3. Interface do Usuário
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - rede_contradito

  # 4. Persistência
  banco_dados:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contradito
    ports:
      - "5432:5432" # Mantido exposto para você conseguir inspecionar via DBeaver/PgAdmin localmente
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_contradito

volumes:
  postgres_data:

# Criação explícita da rede privada do projeto
networks:
  rede_contradito:
    driver: bridge